### ISSUE TITLE
Remove use of `mode: all`

### ISSUE THREAD

**Issue by pokey** [talonhub/community#1122]
Do we want to stop using `mode: all`?  It seems like it could be surprising if a user creates a mode and unexpected commands are active

See also https://github.com/knausj85/knausj_talon/issues/603

**Comment by pokey** [comment]
wait, `all` is a mode?  I thought `mode: all` was a special thing

**Comment by rntz** [comment]
`all` is a mode according to `scope.get("mode")`

**Comment by rntz** [comment]
counterpoint: folks may want `go to sleep` to be active in all modes.

**Comment by nriley** [comment]
We talked about this on the maintenance session today.

* We were generally in agreement that removing "mode: all" and "not mode" from all files makes sense
* Andreas felt that it makes sense to have a separate Talon file for each mode
* We could consider a configurable "what happens when I wake up or sleep Talon" rather than separate commands, then each command implementation would be a single line of TalonScript (e.g., the ones that hide various elements of the knausj help system)
* Or at the least we should comment the difference between "welcome back" and "Talon wake", etc.
