### ISSUE TITLE
Systematize handling of delimiters

### ISSUE THREAD

**Issue by rntz** [talonhub/community#546]
We have a lot of delimiter-related commands, like `args` and `empty [escape] (string|dubstring)` and `inside (bracket|quotes|percent)` and `(percent|pipe|square) that`, mostly living in `symbols.talon`, generally of the forms

- `[empty] [escaped] <delimiter-name>`
- `inside <delimiter-or-punctuation-name>`
- `<delimiter-or-punctuation-name> that`

But it's not super consistent which ones exist and which don't and what they're all named. It would be good to systematize them using some lists/captures. I have a system locally for this and have been using it for a while and like it, but its conventions don't quite line up with the existing knausj commands (eg. it collides with some knausj formatter names). Not sure what the "right" systematization of the existing commands even ought to be. Thoughts?

**Comment by nriley** [comment]
I don't mind the empty/inside/that behavior, but find the names of the individual delimiters by default in knausj…far from what I would naturally say.  (You can see what I've done in my fork: https://github.com/nriley/knausj_talon/blob/43eae5d5/text/symbols.talon)

We may want to allow customization of delimiters (e.g. "bracket", "brace", "quote") like we do for modifiers.

**Comment by rntz** [comment]
I've come up with a systematization of this that I'm happy with, here it is: https://gist.github.com/rntz/e548ff20a28f9e9bd7c6bad8466670d4

I think we could get it pretty close to the current knausj behavior.

**Comment by pokey** [comment]
That's really nice @rntz!  The only things I'd consider changing:

- "angle" => "diamond", for consistency with other visual pair representations, and to avoid conflict with "angle" for left delimiter itself
- why do you don't you use the capture for the last talon command instead of the list?
- I'd consider calling the list "left_delimiter"

**Comment by pokey** [comment]
We just discussed this issue in a recent Cursorless meet-up, in the context of https://github.com/cursorless-dev/cursorless/pull/2193

Here's where we landed:

## End goal

- Create a list like the one proposed by @rntz in https://gist.github.com/rntz/e548ff20a28f9e9bd7c6bad8466670d4, but use a `.talon-list` file (I don't think those existed when @rntz originally wrote that gist). I think we'd lean towards `user.paired_delimiter` for the name of the list, but that detail's not too important
- Include all the delimiters that @rntz has, though we'd lean towards adding one for a pair of spaces, to replace `"padding"`
- Leverage this list in Cursorless in place of the `user.cursorless_wrapper_selectable_paired_delimiter` list, so we'd be able to use it both for the cursorless wrap actions (eg `"round wrap"` / `"round switch"`) and delimiter pair scopes (eg `"take round"`)
- If we included spaces, we'd prob turn pairs of spaces into a Cursorless pseudo-scope. It's not a completely valid scope, because the pairs overlap, and "every" doesn't make sense. But there is a reasonable way to handle all other parts of the scope grammar ("next", containing, "first", etc). This is actually a common request
- We'd move `"pair"` into `modifier_scopes.csv`. It might be a bit unexpected for it not to appear with the other pairs, but it is quite different from them, and can't be in the same list because shouldn't be usable for anything other than as a scope (eg wrapping makes no sense)

## Migration path

### Assumptions
We assume that the user will upgrade cursorless-talon more frequently than community. While we should fail gracefully if that assumption is violated, it is reasonable to just ask them to upgrade cursorless-talon before proceeding. The converse is not true: if cursorless-talon is newer than community, we should just silently continue to function until they get around to upgrading community

### Approach

- Introduce a tag in community that Cursorless can check to see whether the upgrade has occurred. This tag will always be active once they've upgraded to the commit introducing it
- If the given tag is not active, we continue to use today's `user.cursorless_wrapper_selectable_paired_delimiter` in Cursorless
- If the tag is active, Cursorless uses the new `user.paired_delimiter` list
- If on startup, the tag is active and we detect that their `paired_delimiters.csv` still exists, we offer to modify the entries in the new `paired_delimiters.talon-list` to correspond to their paired delimiter spoken forms. At the same time, we will move their line for `"pair"` into `modifier_scopes.csv`
- We can probably remove this migration code in a year

## Questions

### How do we represent the delimiters?

There is a question of what should appear on the right-hand side of the `talon-list`. There are a few options:

a) Use the opening delimiter, as @rntz has done: `round: (`
b) Use both delimiters, separated by a space: `round: ( )`
c) Use both delimiters, not separated by a space: `round: ()`
d) Use identifiers, eg `parentheses`: `round: parentheses`. Note that that's what we do in Cursorless today

The advantage of b) is that the user could use this syntax if we wanted to support arbitrary matching pairs (https://github.com/cursorless-dev/cursorless/issues/335)

**Comment by pokey** [comment]
Fwiw @AndreasArvidsson and I agreed that would make sense to start with an initial PR that just does the following (it's first couple bullets of sections above):

- Create a list like the one proposed by @rntz in https://gist.github.com/rntz/e548ff20a28f9e9bd7c6bad8466670d4, but use a `.talon-list` file (I don't think those existed when @rntz originally wrote that gist). I think we'd lean towards `user.paired_delimiter` for the name of the list, but that detail's not too important
- Include all the delimiters that @rntz has, though we'd lean towards adding one for a pair of spaces, to replace `"padding"`
- Introduce a tag in community that Cursorless can check to see whether the upgrade has occurred. This tag will always be active once they've upgraded to the commit introducing it
