### ISSUE TITLE
Migrate extension_lang_map to a global Talon list

### ISSUE THREAD

**Issue by wenkokke** [talonhub/community#657]
I think we should migrate the variable extension_lang_map to a Talon list.

Ideally, someone implementing support for a new programming language would not have to modify any existing code, and each language mode would append the programming language name and its file extensions to the global list, which would trigger the creation of a new language mode. I assume that this requires registering an event handler in `code.py`, rather than the current loop which creates language modes once based on a constant mapping.

In the current setup, the mapping is not exposed, which leads to developers copying it into their own project whenever they need to know about language modes and file extensions. For instance, see [talon_hud](https://github.com/chaosparrot/talon_hud/blob/dc45b9fd05146abfb66bcdb2b325fce7e725889a/content/status_bar_poller.py#L45). Such copies naturally get out of sync with the copy in this repository. Furthermore, someone implementing support for a new language must also know to update the list in `talon_hud/status_bar_poller.py` and any other project which uses this mapping.

If approved, I should be able to make this change with minimal guidance, and I would be happy to also update [chaosparrot/talon_hud](https://github.com/chaosparrot/talon_hud).

**Comment by rntz** [comment]
I don't know of a way to append to a talon list rather than simply overriding it. Also, talon lists are intended for use in voice commands, not as generic associative-arrays. For instance, I think grabbing the value of a talon list currently requires mucking with talon.registry, which is mostly intended for debug use iirc.

It would definitely be nice to support (a) adding to the set of language extensions on a modular way and (b) reading the language extension map from other files. I don't immediately see a good way to do (a). I think (b) could be done by having an action that returns the list of extension mappings, which talon_hud etc would need to call when they try to figure out what language a file uses. Another option would be to keep the mapping in a CSV file.

**Comment by wenkokke** [comment]
What about declaring a global dict in `code.py` and adding to it in each language mode?

**Comment by rntz** [comment]
We generally try to avoid cross-file imports in Talon python scripts, it causes cascading failures (eg. if I'm editing code.py and make a syntax error and save, now every python file that imports code.py will fail to load, possibly making some commands stop working).

This particular case might also interact badly with Talon's auto-reloading of python scripts. If a module has top-level side effects (like mutating another module's global) and then you change the module, it will get reloaded, and the effect will reoccur. That wouldn't be so bad here, since setting a dictionary entry twice is idempotent. It _would_ mean that deleting that file wouldn't remove the corresponding dictionary entry, though.

So, I think that approach would mostly work, but it feels icky.

**Comment by rntz** [comment]
This feels like a problem that would need solving in order to move to a "plugin" model of talon scripts (instead of the current knausj-centric approach), which I know is on @lunixbochs long-term agenda. Might be worth asking for a Talon feature to handle this.

**Comment by wenkokke** [comment]
Currently the functions and libraries GUI stuff use global variables, so I don't see why we'd need a new Talon feature?

**Comment by rntz** [comment]
I don't think we take a global variable defined in one module and mutate it in another. The library and function globals don't seem to do this; afaict they're just caches used for gui state. Cross-module mutation is what worries me, because (as mentioned earlier) I'm not confident it'll always play nice with Talon's auto-reloading, and it requires importing one python module from another.

**Comment by wenkokke** [comment]
> @rntz I don't think we take a global variable defined in one module and mutate it in another.

It's bad practice in general, but, e.g., matplotlib does it.

**Comment by ym-han** [comment]
I like the external csv/json file idea --- is that not feasible?

**Comment by wenkokke** [comment]
I've been using it in my personal set up, and it works just fine.

**Comment by knausj85** [comment]
Closing in favor of https://github.com/talonhub/community/issues/1585
