### ISSUE TITLE
Formatter removes punctuation or symbols

### ISSUE THREAD

**Issue by atacan** [talonhub/community#674]
To Reproduce:
1. Type something with ALLCAPS like "I'D LIKE TO SEE PUNCTUATION HUNDRED%"
2. Select what you typed
3. Give the command "alldown that"
4. The result is "i d like to see punctuation hundred "

**Comment by rntz** [comment]
I think this behavior is intended, because the formatters were originally intended for formatting variable names while programming. But given that they seem to be useful more widely, we might reconsider this behavior.

**Comment by nriley** [comment]
I wonder if it might make sense to separate "prose transformation" from "code/symbol transformation" — a bit like we ended up with "prose_formatter".  So perhaps we need to separate them, e.g., "lowercase that" vs "alldown that".

**Comment by rntz** [comment]
I'd like to avoid creating "duplicate" versions of commands/formatters if we can get away without them, to avoid unnecessary memorization burden. I think the most problematic use-case is actually apostrophes in variable names: clearly `snake John's world` should type `johns_world` not `john's_world`.

I think formatters basically come in two varieties:

1. Those specifically for variable names (snake, smash, camel, hammer, dunder, kebab), which should never produce spaces, apostrophes, etc.
2. Generic ones (all caps, all down, sentence).

I think the "right" behavior is that if your formatter combination involves any type-1 formatter, it should strip punctuation; otherwise it should preserve it. Does that seem right?

There are also some formatters I'm not sure about. I guess eg slash-separated is more like (1) in that it's probably being to generate file paths, which rarely have spaces or apostrophes.

**Comment by rntz** [comment]
Reminder to self: link Andreas Arvidsson's formatter rewrite here, it may be relevant.

**Comment by rntz** [comment]
Cross-linking #768 here.

**Comment by AndreasArvidsson** [comment]
This is now fixed in community formatters
